/* Browser-only state, deliberately versioned so the small app can grow without losing its mind. */
const KEY='random-access-memories-v1',DAY=86400000;
const fresh=()=>({version:1,offsetDays:0,lastVisit:Date.now(),lastProcessedDay:Math.floor(Date.now()/DAY),reminders:[],notes:[],lists:[],memories:[]});
let state=load(); const $=s=>document.querySelector(s),id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8),now=()=>Date.now()+state.offsetDays*DAY,day=()=>Math.floor(now()/DAY),date=n=>new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(n);
function load(){try{let x=JSON.parse(localStorage.getItem(KEY));return x?.version===1?x:fresh()}catch{return fresh()}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{toast('Could not save locally. Your browser is withholding memory.')}}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),3800)}
const esc=x=>String(x).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); const empty=t=>`<div class="empty">${t}</div>`;
/* Stable item/day hashes make apparently probabilistic results repeatable and testable. */
function roll(seed){let h=2166136261;for(let i=0;i<seed.length;i++){h^=seed.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0)/4294967296}
function memories(){let groups={};state.notes.filter(n=>n.topic.trim()).forEach(n=>(groups[n.topic.trim().toLowerCase()]??=[]).push(n));Object.entries(groups).forEach(([topic,ns])=>{if(ns.length<2)return;let m=state.memories.find(x=>x.topic===topic),fragments=ns.slice(-4).map(n=>({title:n.title,text:n.content.slice(0,160)}));if(m)m.fragments=fragments;else state.memories.push({id:id(),topic,createdAt:now(),fragments})})}
/* Notes get one daily roll. Importance sets base risk; each open multiplies it lower, never to zero.
   A forgotten note is replaced with deterministic partial sentences rather than silently deleted. */
function forgetNotes(d){let chance={low:.36,medium:.20,high:.08},out=[];state.notes.forEach(n=>{let p=chance[n.priority]*Math.pow(.82,n.opens||0);if(roll(`${n.id}:note:${d}`)<p){let bits=n.content.match(/[^.!?]+[.!?]*/g)||n.content.split(/\s+/),kept=bits.filter((b,i)=>roll(`${n.id}:${d}:${i}`)>.38),content=(kept.length?kept:[bits[0]||'Something was here.']).join(' ').trim();out.push({...n,id:id(),title:`${n.title} (recalled)`,content,opens:0,createdAt:now()});toast(`“${n.title}” faded and returned incomplete.`)}else out.push(n)});state.notes=out}
/* Around half of lists disappear each day. A surviving list independently loses roughly half its tasks. */
function forgetLists(d){state.lists=state.lists.filter(l=>{if(roll(`${l.id}:list:${d}`)<.5){toast(`The list “${l.name}” has been professionally misplaced.`);return false}let before=l.tasks.length;l.tasks=l.tasks.filter(t=>roll(`${t.id}:task:${d}`)>=.5);if(l.tasks.length<before)toast(`Some tasks in “${l.name}” slipped away.`);return true})}
function process(){let gap=Math.floor((now()-state.lastVisit)/DAY);if(gap>=3){let offset=state.offsetDays;state=fresh();state.offsetDays=offset;state.lastProcessedDay=day();state.lastVisit=now();save();toast('Three quiet days passed. We forgot everything, as promised.');render();return}for(let d=state.lastProcessedDay+1;d<=day();d++){forgetNotes(d);forgetLists(d);state.lastProcessedDay=d}memories();state.lastVisit=now();save();render()}
function render(){ $('#simulated-date').textContent=date(now());$('#app-status').textContent=`${state.notes.length} note${state.notes.length===1?'':'s'}, ${state.reminders.length} reminder${state.reminders.length===1?'':'s'}, and an entirely fallible archive.`;
$('#reminder-list').innerHTML=state.reminders.length?state.reminders.map(r=>{let p=Math.round(r.probability*100);return `<div class="item"><div class="item-top"><span class="item-title">${esc(r.text)}</span><span class="probability"><span class="meter"><i style="width:${p}%"></i></span>${p}% likely</span></div><p class="meta">Attempts: ${r.attempts}. Initial confidence was, correctly, 0%.</p><div class="item-actions"><button data-remind="${r.id}">Repeat notification</button><button class="danger" data-dr="${r.id}">Delete</button></div></div>`}).join(''):empty('No reminders yet. This is the one thing we are reliably remembering.');
$('#note-list').innerHTML=state.notes.length?state.notes.slice().reverse().map(n=>`<div class="item"><div class="item-top"><span class="item-title">${esc(n.title)}</span><span class="priority ${n.priority}">${n.priority} priority</span></div><p class="note-preview">${esc(n.content)}</p><p class="meta">${n.topic?`Topic: ${esc(n.topic)} · `:''}Opened ${n.opens||0} time${n.opens===1?'':'s'} — familiarity protects it.</p><div class="item-actions"><button data-open="${n.id}">Open &amp; reinforce</button><button class="danger" data-dn="${n.id}">Delete</button></div></div>`).join(''):empty('No notes. A blank slate, whether you asked for one or not.');
$('#lists-container').innerHTML=state.lists.length?state.lists.map(l=>`<div class="item"><div class="list-heading"><strong>${esc(l.name)}</strong><button class="danger" data-dl="${l.id}">Forget list</button></div>${l.tasks.length?l.tasks.map(t=>`<label class="task-row ${t.done?'done':''}"><input type="checkbox" data-task="${t.id}" ${t.done?'checked':''}><span>${esc(t.text)}</span></label>`).join(''):'<p class="meta">This list is empty. It is already halfway there.</p>'}<form class="task-form" data-list="${l.id}"><input required maxlength="140" placeholder="Add a task" aria-label="Task for ${esc(l.name)}"><button>Add task</button></form></div>`).join(''):empty('No lists yet. Your plans are exceptionally lightweight.');
$('#memory-list').innerHTML=state.memories.length?state.memories.map(m=>`<div class="memory-card"><h3>${esc(m.topic)}</h3><p>${m.fragments.length} related fragments, stubbornly retained.</p><p class="meta">${m.fragments.map(f=>esc(f.title)).join(' · ')}</p></div>`).join(''):empty('Add at least two notes with the same topic to create a memory we cannot conveniently lose.');}
$('#reminder-form').onsubmit=e=>{e.preventDefault();let text=$('#reminder-text').value.trim();if(!text)return toast('A reminder needs a few words to disappoint you with.');state.reminders.push({id:id(),text,probability:0,attempts:0});e.target.reset();save();render();toast('Reminder saved. Its chance of notifying you is currently 0%.')};
$('#note-form').onsubmit=e=>{e.preventDefault();let title=$('#note-title').value.trim(),content=$('#note-content').value.trim();if(!title||!content)return toast('A note needs a title and a thought first.');state.notes.push({id:id(),title,content,topic:$('#note-topic').value.trim(),priority:$('#note-priority').value,opens:0,createdAt:now()});e.target.reset();memories();save();render();toast('Note filed somewhere moderately questionable.')};
$('#list-form').onsubmit=e=>{e.preventDefault();let name=$('#list-name').value.trim();if(!name)return;state.lists.push({id:id(),name,tasks:[]});e.target.reset();save();render();toast('List created. It has a 50/50 future.')};
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.advance){state.offsetDays+=+b.dataset.advance;process();return}if(b.dataset.remind){let r=state.reminders.find(x=>x.id===b.dataset.remind);r.attempts++;r.probability=1-(1-r.probability)*.65;let ok=roll(`${r.id}:reminder:${r.attempts}`)<r.probability;save();render();toast(ok?`Notification escaped successfully: ${r.text}`:`Notification failed. Odds are now ${Math.round(r.probability*100)}%.`)}if(b.dataset.dr){state.reminders=state.reminders.filter(x=>x.id!==b.dataset.dr);save();render();toast('Reminder deleted with unusual decisiveness.')}if(b.dataset.dn){state.notes=state.notes.filter(x=>x.id!==b.dataset.dn);save();render();toast('Note deleted. Related memories remain judgmentally intact.')}if(b.dataset.dl){state.lists=state.lists.filter(x=>x.id!==b.dataset.dl);save();render();toast('List deliberately forgotten.')}if(b.dataset.open){let n=state.notes.find(x=>x.id===b.dataset.open);if(!n)return;n.opens=(n.opens||0)+1;$('#dialog-topic').textContent=n.topic?`Topic: ${n.topic}`:'Uncategorised thought';$('#dialog-title').textContent=n.title;$('#dialog-content').textContent=n.content;$('#note-dialog').showModal();save();render()}if(b.id==='close-dialog')$('#note-dialog').close()});
document.addEventListener('change',e=>{if(!e.target.dataset.task)return;state.lists.forEach(l=>l.tasks.forEach(t=>{if(t.id===e.target.dataset.task)t.done=e.target.checked}));save();render()});
document.addEventListener('submit',e=>{let list=e.target.dataset.list;if(!list)return;e.preventDefault();let text=e.target.querySelector('input').value.trim(),l=state.lists.find(x=>x.id===list);if(!text)return toast('An empty task is too easy to forget.');if(!l)return toast('That list has already wandered off.');l.tasks.push({id:id(),text,done:false});save();render();toast('Task added. Its odds are not reassuring.')});
$('#note-dialog').onclick=e=>{if(e.target===$('#note-dialog'))$('#note-dialog').close()};process();
